Support upstream shenandoah-visualizer encoding
earthling-amzn/shenandoah-visualizer pull request #4
Opened 2022-07-12 16:54 UTC by cfumiwu

Add new protocolVersion variable and new decoding method version_phase.

2022-07-12 19:03 UTC, earthling-amzn requested changes

2022-07-12 19:03 UTC, earthling-amzn commented on src/test/java/org/openjdk/shenandoah/DecoderTest.java
> + * ====
Looks like there is some duplication in this header. Also, you can put Amazon in the copyright and update the year.

2022-07-12 19:03 UTC, earthling-amzn commented on src/test/java/org/openjdk/shenandoah/DecoderTest.java
> +    Snapshot snapshot_version1_idle;
Can we changes these to `camelCase` for consistency with other code?

2022-07-12 19:03 UTC, earthling-amzn commented on src/main/java/org/openjdk/shenandoah/DataLogProvider.java
> +        long protocolVersion = 2;
There should be a symbolic constant for these version numbers. Maybe `ORIGINAL_VERSION == 1` and `LATEST_VERSION == 2`?

2022-07-12 19:25 UTC, cfumiwu commented on src/main/java/org/openjdk/shenandoah/DataLogProvider.java
> +        long protocolVersion = 2;
The symbolic constant is in the OpenJDKTipSrc, but I can also add them in the visualizer. However, should I also add it in the `DataProvider` file?

2022-07-12 20:35 UTC, earthling-amzn requested changes
Make constants be `static final` and use them where we can.

2022-07-12 20:35 UTC, earthling-amzn commented on src/main/java/org/openjdk/shenandoah/DataProvider.java
> +    private long ORIGINAL_VERSION = 1;
Should be `static final`, put it near other constants.

2022-07-12 20:35 UTC, earthling-amzn commented on src/main/java/org/openjdk/shenandoah/DataProvider.java
> +    private static final Snapshot DISCONNECTED = new Snapshot(0, 1024, 2, Collections.emptyList(), 0, new Histogram(2));
The `2` argument should be `LATEST_VERSION` right?

2022-07-12 20:35 UTC, earthling-amzn commented on src/main/java/org/openjdk/shenandoah/DataLogProvider.java
> +    private long LATEST_VERSION = 2;
Should be `static final` and we can use this instead of the `2` argument for `DISCONNECTED` `Snapshot` constructor.

2022-07-14 16:57 UTC, earthling-amzn approved these changes

2022-07-14 16:58 UTC, merged